call %~dp0\DeathKnight\DK_All_RaceSimulation.bat 1T nopause
call %~dp0\DemonHunter\DH_All_RaceSimulation.bat 1T nopause
call %~dp0\Druid\Druid_All_RaceSimulation.bat 1T nopause
call %~dp0\Hunter\Hunter_All_RaceSimulation.bat 1T nopause
call %~dp0\Mage\Mage_All_RaceSimulation.bat 1T nopause
call %~dp0\Monk\Monk_All_RaceSimulation.bat 1T nopause
call %~dp0\Paladin\Paladin_All_RaceSimulation.bat 1T nopause
call %~dp0\Priest\Priest_All_RaceSimulation.bat 1T nopause
call %~dp0\Rogue\Rogue_All_RaceSimulation.bat 1T nopause
call %~dp0\Shaman\Shaman_All_RaceSimulation.bat 1T nopause
call %~dp0\Warlock\Warlock_All_RaceSimulation.bat 1T nopause
call %~dp0\Warrior\Warrior_All_RaceSimulation.bat 1T nopause

call %~dp0\DeathKnight\DK_All_RelicSimulation.bat 1T nopause
call %~dp0\DemonHunter\DH_All_RelicSimulation.bat 1T nopause
call %~dp0\Druid\Druid_All_RelicSimulation.bat 1T nopause
call %~dp0\Hunter\Hunter_All_RelicSimulation.bat 1T nopause
call %~dp0\Mage\Mage_All_RelicSimulation.bat 1T nopause
call %~dp0\Monk\Monk_All_RelicSimulation.bat 1T nopause
call %~dp0\Paladin\Paladin_All_RelicSimulation.bat 1T nopause
call %~dp0\Priest\Priest_All_RelicSimulation.bat 1T nopause
call %~dp0\Rogue\Rogue_All_RelicSimulation.bat 1T nopause
call %~dp0\Shaman\Shaman_All_RelicSimulation.bat 1T nopause
call %~dp0\Warlock\Warlock_All_RelicSimulation.bat 1T nopause
call %~dp0\Warrior\Warrior_All_RelicSimulation.bat 1T nopause

call %~dp0\DeathKnight\DK_All_TrinketSimulation.bat 1T nopause
call %~dp0\DemonHunter\DH_All_TrinketSimulation.bat 1T nopause
call %~dp0\Druid\Druid_All_TrinketSimulation.bat 1T nopause
call %~dp0\Hunter\Hunter_All_TrinketSimulation.bat 1T nopause
call %~dp0\Mage\Mage_All_TrinketSimulation.bat 1T nopause
call %~dp0\Monk\Monk_All_TrinketSimulation.bat 1T nopause
call %~dp0\Paladin\Paladin_All_TrinketSimulation.bat 1T nopause
call %~dp0\Priest\Priest_All_TrinketSimulation.bat 1T nopause
call %~dp0\Rogue\Rogue_All_TrinketSimulation.bat 1T nopause
call %~dp0\Shaman\Shaman_All_TrinketSimulation.bat 1T nopause
call %~dp0\Warlock\Warlock_All_TrinketSimulation.bat 1T nopause
call %~dp0\Warrior\Warrior_All_TrinketSimulation.bat 1T nopause

call %~dp0\DeathKnight\DK_All_Combinator.bat 1T nopause
call %~dp0\DemonHunter\DH_All_Combinator.bat 1T nopause
call %~dp0\Druid\Druid_All_Combinator.bat 1T nopause
call %~dp0\Hunter\Hunter_All_Combinator.bat 1T nopause
call %~dp0\Mage\Mage_All_Combinator.bat 1T nopause
call %~dp0\Monk\Monk_All_Combinator.bat 1T nopause
call %~dp0\Paladin\Paladin_All_Combinator.bat 1T nopause
call %~dp0\Priest\Priest_All_Combinator.bat 1T nopause
call %~dp0\Rogue\Rogue_All_Combinator.bat 1T nopause
call %~dp0\Shaman\Shaman_All_Combinator.bat 1T nopause
call %~dp0\Warlock\Warlock_All_Combinator.bat 1T nopause
call %~dp0\Warrior\Warrior_All_Combinator.bat 1T nopause

call %~dp0\DeathKnight\DK_All_RaceSimulation.bat 2T nopause
call %~dp0\DemonHunter\DH_All_RaceSimulation.bat 2T nopause
call %~dp0\Druid\Druid_All_RaceSimulation.bat 2T nopause
call %~dp0\Hunter\Hunter_All_RaceSimulation.bat 2T nopause
call %~dp0\Mage\Mage_All_RaceSimulation.bat 2T nopause
call %~dp0\Monk\Monk_All_RaceSimulation.bat 2T nopause
call %~dp0\Paladin\Paladin_All_RaceSimulation.bat 2T nopause
call %~dp0\Priest\Priest_All_RaceSimulation.bat 2T nopause
call %~dp0\Rogue\Rogue_All_RaceSimulation.bat 2T nopause
call %~dp0\Shaman\Shaman_All_RaceSimulation.bat 2T nopause
call %~dp0\Warlock\Warlock_All_RaceSimulation.bat 2T nopause
call %~dp0\Warrior\Warrior_All_RaceSimulation.bat 2T nopause

call %~dp0\DeathKnight\DK_All_RaceSimulation.bat 3T nopause
call %~dp0\DemonHunter\DH_All_RaceSimulation.bat 3T nopause
call %~dp0\Druid\Druid_All_RaceSimulation.bat 3T nopause
call %~dp0\Hunter\Hunter_All_RaceSimulation.bat 3T nopause
call %~dp0\Mage\Mage_All_RaceSimulation.bat 3T nopause
call %~dp0\Monk\Monk_All_RaceSimulation.bat 3T nopause
call %~dp0\Paladin\Paladin_All_RaceSimulation.bat 3T nopause
call %~dp0\Priest\Priest_All_RaceSimulation.bat 3T nopause
call %~dp0\Rogue\Rogue_All_RaceSimulation.bat 3T nopause
call %~dp0\Shaman\Shaman_All_RaceSimulation.bat 3T nopause
call %~dp0\Warlock\Warlock_All_RaceSimulation.bat 3T nopause
call %~dp0\Warrior\Warrior_All_RaceSimulation.bat 3T nopause

call %~dp0\DeathKnight\DK_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\DemonHunter\DH_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Druid\Druid_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Hunter\Hunter_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Mage\Mage_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Monk\Monk_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Paladin\Paladin_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Priest\Priest_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Rogue\Rogue_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Shaman\Shaman_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Warlock\Warlock_All_RaceSimulation.bat 1T_Adds nopause
call %~dp0\Warrior\Warrior_All_RaceSimulation.bat 1T_Adds nopause

call %~dp0\DeathKnight\DK_All_RelicSimulation.bat 2T nopause
call %~dp0\DemonHunter\DH_All_RelicSimulation.bat 2T nopause
call %~dp0\Druid\Druid_All_RelicSimulation.bat 2T nopause
call %~dp0\Hunter\Hunter_All_RelicSimulation.bat 2T nopause
call %~dp0\Mage\Mage_All_RelicSimulation.bat 2T nopause
call %~dp0\Monk\Monk_All_RelicSimulation.bat 2T nopause
call %~dp0\Paladin\Paladin_All_RelicSimulation.bat 2T nopause
call %~dp0\Priest\Priest_All_RelicSimulation.bat 2T nopause
call %~dp0\Rogue\Rogue_All_RelicSimulation.bat 2T nopause
call %~dp0\Shaman\Shaman_All_RelicSimulation.bat 2T nopause
call %~dp0\Warlock\Warlock_All_RelicSimulation.bat 2T nopause
call %~dp0\Warrior\Warrior_All_RelicSimulation.bat 2T nopause

call %~dp0\DeathKnight\DK_All_TrinketSimulation.bat 2T nopause
call %~dp0\DemonHunter\DH_All_TrinketSimulation.bat 2T nopause
call %~dp0\Druid\Druid_All_TrinketSimulation.bat 2T nopause
call %~dp0\Hunter\Hunter_All_TrinketSimulation.bat 2T nopause
call %~dp0\Mage\Mage_All_TrinketSimulation.bat 2T nopause
call %~dp0\Monk\Monk_All_TrinketSimulation.bat 2T nopause
call %~dp0\Paladin\Paladin_All_TrinketSimulation.bat 2T nopause
call %~dp0\Priest\Priest_All_TrinketSimulation.bat 2T nopause
call %~dp0\Rogue\Rogue_All_TrinketSimulation.bat 2T nopause
call %~dp0\Shaman\Shaman_All_TrinketSimulation.bat 2T nopause
call %~dp0\Warlock\Warlock_All_TrinketSimulation.bat 2T nopause
call %~dp0\Warrior\Warrior_All_TrinketSimulation.bat 2T nopause

call %~dp0\DeathKnight\DK_All_RelicSimulation.bat 3T nopause
call %~dp0\DemonHunter\DH_All_RelicSimulation.bat 3T nopause
call %~dp0\Druid\Druid_All_RelicSimulation.bat 3T nopause
call %~dp0\Hunter\Hunter_All_RelicSimulation.bat 3T nopause
call %~dp0\Mage\Mage_All_RelicSimulation.bat 3T nopause
call %~dp0\Monk\Monk_All_RelicSimulation.bat 3T nopause
call %~dp0\Paladin\Paladin_All_RelicSimulation.bat 3T nopause
call %~dp0\Priest\Priest_All_RelicSimulation.bat 3T nopause
call %~dp0\Rogue\Rogue_All_RelicSimulation.bat 3T nopause
call %~dp0\Shaman\Shaman_All_RelicSimulation.bat 3T nopause
call %~dp0\Warlock\Warlock_All_RelicSimulation.bat 3T nopause
call %~dp0\Warrior\Warrior_All_RelicSimulation.bat 3T nopause

call %~dp0\DeathKnight\DK_All_TrinketSimulation.bat 3T nopause
call %~dp0\DemonHunter\DH_All_TrinketSimulation.bat 3T nopause
call %~dp0\Druid\Druid_All_TrinketSimulation.bat 3T nopause
call %~dp0\Hunter\Hunter_All_TrinketSimulation.bat 3T nopause
call %~dp0\Mage\Mage_All_TrinketSimulation.bat 3T nopause
call %~dp0\Monk\Monk_All_TrinketSimulation.bat 3T nopause
call %~dp0\Paladin\Paladin_All_TrinketSimulation.bat 3T nopause
call %~dp0\Priest\Priest_All_TrinketSimulation.bat 3T nopause
call %~dp0\Rogue\Rogue_All_TrinketSimulation.bat 3T nopause
call %~dp0\Shaman\Shaman_All_TrinketSimulation.bat 3T nopause
call %~dp0\Warlock\Warlock_All_TrinketSimulation.bat 3T nopause
call %~dp0\Warrior\Warrior_All_TrinketSimulation.bat 3T nopause

call %~dp0\DeathKnight\DK_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\DemonHunter\DH_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Druid\Druid_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Hunter\Hunter_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Mage\Mage_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Monk\Monk_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Paladin\Paladin_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Priest\Priest_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Rogue\Rogue_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Shaman\Shaman_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Warlock\Warlock_All_RelicSimulation.bat 1T_Adds nopause
call %~dp0\Warrior\Warrior_All_RelicSimulation.bat 1T_Adds nopause

call %~dp0\DeathKnight\DK_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\DemonHunter\DH_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Druid\Druid_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Hunter\Hunter_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Mage\Mage_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Monk\Monk_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Paladin\Paladin_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Priest\Priest_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Rogue\Rogue_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Shaman\Shaman_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Warlock\Warlock_All_TrinketSimulation.bat 1T_Adds nopause
call %~dp0\Warrior\Warrior_All_TrinketSimulation.bat 1T_Adds nopause

call %~dp0\DeathKnight\DK_All_Combinator.bat 2T nopause
call %~dp0\DemonHunter\DH_All_Combinator.bat 2T nopause
call %~dp0\Druid\Druid_All_Combinator.bat 2T nopause
call %~dp0\Hunter\Hunter_All_Combinator.bat 2T nopause
call %~dp0\Mage\Mage_All_Combinator.bat 2T nopause
call %~dp0\Monk\Monk_All_Combinator.bat 2T nopause
call %~dp0\Paladin\Paladin_All_Combinator.bat 2T nopause
call %~dp0\Priest\Priest_All_Combinator.bat 2T nopause
call %~dp0\Rogue\Rogue_All_Combinator.bat 2T nopause
call %~dp0\Shaman\Shaman_All_Combinator.bat 2T nopause
call %~dp0\Warlock\Warlock_All_Combinator.bat 2T nopause
call %~dp0\Warrior\Warrior_All_Combinator.bat 2T nopause

call %~dp0\DeathKnight\DK_All_Combinator.bat 3T nopause
call %~dp0\DemonHunter\DH_All_Combinator.bat 3T nopause
call %~dp0\Druid\Druid_All_Combinator.bat 3T nopause
call %~dp0\Hunter\Hunter_All_Combinator.bat 3T nopause
call %~dp0\Mage\Mage_All_Combinator.bat 3T nopause
call %~dp0\Monk\Monk_All_Combinator.bat 3T nopause
call %~dp0\Paladin\Paladin_All_Combinator.bat 3T nopause
call %~dp0\Priest\Priest_All_Combinator.bat 3T nopause
call %~dp0\Rogue\Rogue_All_Combinator.bat 3T nopause
call %~dp0\Shaman\Shaman_All_Combinator.bat 3T nopause
call %~dp0\Warlock\Warlock_All_Combinator.bat 3T nopause
call %~dp0\Warrior\Warrior_All_Combinator.bat 3T nopause

call %~dp0\DeathKnight\DK_All_Combinator.bat 1T_Adds nopause
call %~dp0\DemonHunter\DH_All_Combinator.bat 1T_Adds nopause
call %~dp0\Druid\Druid_All_Combinator.bat 1T_Adds nopause
call %~dp0\Hunter\Hunter_All_Combinator.bat 1T_Adds nopause
call %~dp0\Mage\Mage_All_Combinator.bat 1T_Adds nopause
call %~dp0\Monk\Monk_All_Combinator.bat 1T_Adds nopause
call %~dp0\Paladin\Paladin_All_Combinator.bat 1T_Adds nopause
call %~dp0\Priest\Priest_All_Combinator.bat 1T_Adds nopause
call %~dp0\Rogue\Rogue_All_Combinator.bat 1T_Adds nopause
call %~dp0\Shaman\Shaman_All_Combinator.bat 1T_Adds nopause
call %~dp0\Warlock\Warlock_All_Combinator.bat 1T_Adds nopause
call %~dp0\Warrior\Warrior_All_Combinator.bat 1T_Adds nopause

@pause
